version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    networks:
      - dcompose

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - dcompose

networks:
  dcompose:
    driver: bridge
